#!/usr/bin/env bash

if [ -z "$VERSION" ]; then
    VERSION=$(node -e "console.log(require('./package.json').version)")
fi

if [ -z "$REPO" ]; then
    REPO=$(node -e "console.log(require('./package.json').name.split('/').pop())")
fi

echo "Building $REPO $VERSION"

docker build -t "$REPO:$VERSION" "$@" .
